name: Send notification on push
on: [push]
  #schedule:
#早上10点0分，周六周日不用
  #  - cron: '0 2 * * 1-5'
jobs:
  send-msg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # 纯文本类型
      - name: WeChat Work notification by text
        uses: yihah/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: "记得填写一下每日计划"
          mentioned_list: '["@all"]'
