name: Send notification on push
on: [push]
schedule:
	#早上10点0分
    - cron: '0 2 * * *'
jobs:
  send-msg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # 纯文本类型
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=84eabebc-0240-40d7-9d3d-6159bbad74a1}}
        with:
          msgtype: text
          content: "记得填写一下每日计划"
          mentioned_list: '["@all"]'
