name: Send notification on push
on:
  schedule:
#早上10点0分，周六周日不用
    - cron: "5 3 * * 1-5"
jobs:
  send-msg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      #[ubuntu-latest, windows-latest, macos-latest] 选一个就行，不然会发3条
        os: [ubuntu-latest]
    steps:
      # 纯文本类型
      - name: WeChat Work notification by text
        uses: yihaha/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: "记得填写一下每日计划\n https://doc.weixin.qq.com/sheet/e3_AaYA9AYuADEQgI7NQ3hS1GmAFD21c?scode=AC0AuAecAAo06sndciAaYA9AYuADE"
          mentioned_list: '["@all"]'
